import { GoogleGenAI } from '@google/genai';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { messages, systemPrompt, model, temperature, maxTokens, geminiApiKey } = req.body;

  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Transfer-Encoding', 'chunked');

  try {
    const apiKey = geminiApiKey || process.env.GEMINI_API_KEY;

    if (apiKey && (model?.startsWith('gemini') || !model)) {
      const ai = new GoogleGenAI({ apiKey });
      const modelName = model?.includes('pro') ? 'gemini-2.5-pro' : 'gemini-2.5-flash';

      const contents = messages.map(m => ({
        role: m.role === 'assistant' ? 'model' : 'user',
        parts: [{ text: m.content }]
      }));

      const streamResult = await ai.models.generateContentStream({
        model: modelName,
        contents,
        config: {
          systemInstruction: systemPrompt ? { parts: [{ text: systemPrompt }] } : undefined,
          temperature: temperature || 0.7,
          maxOutputTokens: maxTokens || 2048,
        }
      });

      for await (const chunk of streamResult.stream) {
        if (chunk.text) {
          res.write(chunk.text);
        }
      }
      res.end();
      return;
    }

    // Default built-in smart engine fallback
    const userPrompt = messages[messages.length - 1]?.content || 'Hello';
    const smartResponse = `NexusAI Server Processed: "${userPrompt.slice(0, 100)}"\n\nHere is a detailed, structured response generated by the Nexus Server Engine. Everything is configured and streaming cleanly!`;

    for (const word of smartResponse.split(' ')) {
      res.write(word + ' ');
      await new Promise(r => setTimeout(r, 20));
    }
    res.end();
  } catch (error) {
    console.error('Vercel streaming error:', error);
    res.status(500).write(`\nError: ${error.message || 'Internal server error'}`);
    res.end();
  }
}
